package com.luusean.studentscannerlab.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.luusean.studentscannerlab.database.EventObject;
import com.luusean.studentscannerlab.database.EventStudentObject;

import com.luusean.studentscannerlab.database.EventObjectDao;
import com.luusean.studentscannerlab.database.EventStudentObjectDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig eventObjectDaoConfig;
    private final DaoConfig eventStudentObjectDaoConfig;

    private final EventObjectDao eventObjectDao;
    private final EventStudentObjectDao eventStudentObjectDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        eventObjectDaoConfig = daoConfigMap.get(EventObjectDao.class).clone();
        eventObjectDaoConfig.initIdentityScope(type);

        eventStudentObjectDaoConfig = daoConfigMap.get(EventStudentObjectDao.class).clone();
        eventStudentObjectDaoConfig.initIdentityScope(type);

        eventObjectDao = new EventObjectDao(eventObjectDaoConfig, this);
        eventStudentObjectDao = new EventStudentObjectDao(eventStudentObjectDaoConfig, this);

        registerDao(EventObject.class, eventObjectDao);
        registerDao(EventStudentObject.class, eventStudentObjectDao);
    }
    
    public void clear() {
        eventObjectDaoConfig.clearIdentityScope();
        eventStudentObjectDaoConfig.clearIdentityScope();
    }

    public EventObjectDao getEventObjectDao() {
        return eventObjectDao;
    }

    public EventStudentObjectDao getEventStudentObjectDao() {
        return eventStudentObjectDao;
    }

}
