package com.luusean.studentscannerlab.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.luusean.studentscannerlab.database.EventObject;
import com.luusean.studentscannerlab.database.EventStudentObject;
import com.luusean.studentscannerlab.database.StudentObject;

import com.luusean.studentscannerlab.database.EventObjectDao;
import com.luusean.studentscannerlab.database.EventStudentObjectDao;
import com.luusean.studentscannerlab.database.StudentObjectDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig eventObjectDaoConfig;
    private final DaoConfig eventStudentObjectDaoConfig;
    private final DaoConfig studentObjectDaoConfig;

    private final EventObjectDao eventObjectDao;
    private final EventStudentObjectDao eventStudentObjectDao;
    private final StudentObjectDao studentObjectDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        eventObjectDaoConfig = daoConfigMap.get(EventObjectDao.class).clone();
        eventObjectDaoConfig.initIdentityScope(type);

        eventStudentObjectDaoConfig = daoConfigMap.get(EventStudentObjectDao.class).clone();
        eventStudentObjectDaoConfig.initIdentityScope(type);

        studentObjectDaoConfig = daoConfigMap.get(StudentObjectDao.class).clone();
        studentObjectDaoConfig.initIdentityScope(type);

        eventObjectDao = new EventObjectDao(eventObjectDaoConfig, this);
        eventStudentObjectDao = new EventStudentObjectDao(eventStudentObjectDaoConfig, this);
        studentObjectDao = new StudentObjectDao(studentObjectDaoConfig, this);

        registerDao(EventObject.class, eventObjectDao);
        registerDao(EventStudentObject.class, eventStudentObjectDao);
        registerDao(StudentObject.class, studentObjectDao);
    }
    
    public void clear() {
        eventObjectDaoConfig.clearIdentityScope();
        eventStudentObjectDaoConfig.clearIdentityScope();
        studentObjectDaoConfig.clearIdentityScope();
    }

    public EventObjectDao getEventObjectDao() {
        return eventObjectDao;
    }

    public EventStudentObjectDao getEventStudentObjectDao() {
        return eventStudentObjectDao;
    }

    public StudentObjectDao getStudentObjectDao() {
        return studentObjectDao;
    }

}
